import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../ui/nav";
import Footer from "../ui/footer";
import WorkDays from "@/ui/workDays";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <meta name="description" content={"Nomopo Store – Your one-stop shop for the latest mobile phones, quality accessories, and unbeatable deals."} />
        <meta name="keywords" content="mobile phones, accessories, smartphones, Nomopo Store, gadgets" />
        <meta property="og:title" content={"Nomopo Store | Mobile Phones & Accessories"} />
        <meta property="og:description" content="Shop the latest phones & accessories at Nomopo Store – Great prices, trusted quality." />
        <meta property="og:image" content="/instore.jpg" />
      
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="px-2 sm:px-5 bg-gray-900">
          
          <Nav />
          {children}
          <WorkDays />
          <Footer />
        </div>
      </body>
    </html>
  );
}
